# Generated by Django 6.0.3 on 2026-03-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='security_answer_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='security_answer_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='security_answer_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='security_question_1',
            field=models.CharField(blank=True, choices=[('q1', '¿Cuál es el nombre de tu primera mascota?'), ('q2', '¿En qué ciudad naciste?'), ('q3', '¿Cual es el nombre de soltera de tu madre?'), ('q4', '¿Cuál fue el modelo de tu primer coche?'), ('q5', '¿Cuál es el nombre de tu escuela primaria?')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='security_question_2',
            field=models.CharField(blank=True, choices=[('q1', '¿Cuál es el nombre de tu primera mascota?'), ('q2', '¿En qué ciudad naciste?'), ('q3', '¿Cual es el nombre de soltera de tu madre?'), ('q4', '¿Cuál fue el modelo de tu primer coche?'), ('q5', '¿Cuál es el nombre de tu escuela primaria?')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='security_question_3',
            field=models.CharField(blank=True, choices=[('q1', '¿Cuál es el nombre de tu primera mascota?'), ('q2', '¿En qué ciudad naciste?'), ('q3', '¿Cual es el nombre de soltera de tu madre?'), ('q4', '¿Cuál fue el modelo de tu primer coche?'), ('q5', '¿Cuál es el nombre de tu escuela primaria?')], max_length=2, null=True),
        ),
    ]
