# Generated by Django 6.0.3 on 2026-03-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_buyerprofile_security_answer_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='security_question_1',
            field=models.CharField(blank=True, choices=[('q1', '¿Cuál es tu color favorito?'), ('q2', '¿En qué ciudad naciste?'), ('q3', '¿Cual es el nombre de soltera de tu madre?'), ('q4', '¿Cuál fue el modelo de tu primer coche?'), ('q5', '¿Cuál es el nombre de tu escuela primaria?')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='security_question_2',
            field=models.CharField(blank=True, choices=[('q1', '¿Cuál es tu color favorito?'), ('q2', '¿En qué ciudad naciste?'), ('q3', '¿Cual es el nombre de soltera de tu madre?'), ('q4', '¿Cuál fue el modelo de tu primer coche?'), ('q5', '¿Cuál es el nombre de tu escuela primaria?')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='security_question_3',
            field=models.CharField(blank=True, choices=[('q1', '¿Cuál es tu color favorito?'), ('q2', '¿En qué ciudad naciste?'), ('q3', '¿Cual es el nombre de soltera de tu madre?'), ('q4', '¿Cuál fue el modelo de tu primer coche?'), ('q5', '¿Cuál es el nombre de tu escuela primaria?')], max_length=2, null=True),
        ),
    ]
