# Generated by Django 6.0.3 on 2026-03-07 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceramic',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum.artwork')),
                ('material', models.CharField(max_length=100)),
                ('technique', models.CharField(max_length=100)),
                ('glaze_type', models.CharField(max_length=100, verbose_name='Tipo de esmalte')),
                ('height', models.DecimalField(decimal_places=2, help_text='Altura en cm', max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, help_text='Ancho en cm', max_digits=8)),
            ],
            options={
                'verbose_name': 'Cerámica',
                'verbose_name_plural': 'Cerámicas',
            },
            bases=('museum.artwork',),
        ),
        migrations.CreateModel(
            name='Goldsmithing',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum.artwork')),
                ('material', models.CharField(choices=[('gold', 'Oro'), ('silver', 'Plata'), ('bronze', 'Bronce'), ('copper', 'Cobre')], max_length=50)),
                ('object_type', models.CharField(choices=[('ring', 'Anillo'), ('necklace', 'Collar'), ('bracelet', 'Pulsera')], max_length=50, verbose_name='Tipo de objeto')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Peso en gramos', max_digits=8)),
                ('gemstones', models.CharField(blank=True, max_length=200, verbose_name='Piedras preciosas')),
            ],
            options={
                'verbose_name': 'Orfebrería',
                'verbose_name_plural': 'Orfebrerías',
            },
            bases=('museum.artwork',),
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum.artwork')),
                ('technique', models.CharField(choices=[('oil', 'Óleo'), ('acrylic', 'Acrílico'), ('watercolor', 'Acuarela')], max_length=50)),
                ('support', models.CharField(choices=[('canvas', 'Lienzo'), ('wood', 'Madera'), ('paper', 'Papel')], max_length=50)),
                ('height', models.DecimalField(decimal_places=2, help_text='Altura en cm', max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, help_text='Ancho en cm', max_digits=8)),
            ],
            options={
                'verbose_name': 'Pintura',
                'verbose_name_plural': 'Pinturas',
            },
            bases=('museum.artwork',),
        ),
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum.artwork')),
                ('photo_type', models.CharField(choices=[('digital', 'Digital'), ('analog', 'Analógica')], max_length=50, verbose_name='Tipo')),
                ('camera', models.CharField(max_length=200)),
                ('technique', models.CharField(choices=[('bw', 'Blanco y negro'), ('color', 'Color')], max_length=50, verbose_name='Técnica')),
                ('height', models.DecimalField(decimal_places=2, help_text='Altura en cm', max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, help_text='Ancho en cm', max_digits=8)),
            ],
            options={
                'verbose_name': 'Fotografía',
                'verbose_name_plural': 'Fotografías',
            },
            bases=('museum.artwork',),
        ),
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum.artwork')),
                ('material', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, help_text='Altura en cm', max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, help_text='Ancho en cm', max_digits=8)),
                ('depth', models.DecimalField(decimal_places=2, help_text='Profundidad en cm', max_digits=8)),
            ],
            options={
                'verbose_name': 'Escultura',
                'verbose_name_plural': 'Esculturas',
            },
            bases=('museum.artwork',),
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='attributes',
        ),
    ]
