# Generated by Django 6.0.3 on 2026-03-08 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_ceramic_goldsmithing_painting_photography_sculpture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('security_code_used', models.CharField(max_length=10)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='museum.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('artwork', 'user')},
            },
        ),
    ]
