# Generated by Django 6.0.3 on 2026-03-09 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Porcentaje de ganancia del museo (5% a 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Tarjeta de Crédito'), ('BANK_TRANSFER', 'Transferencia Bancaria'), ('CASH', 'Efectivo'), ('OTHER', 'Otro')], default='CREDIT_CARD', max_length=50, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='goldsmithing',
            name='object_type',
            field=models.CharField(max_length=50, verbose_name='Tipo de objeto'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
