# Generated by Django 6.0.3 on 2026-03-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_artist_commission_percentage_sale_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='Dirección de Envío'),
        ),
    ]
